### ISSUE TITLE
divide cx into separate repos

### ISSUE THREAD

**Issue by svinota** [svinota/cx#2]
We should turn the cx repo into several separate repos -- cxnet and so on -- to ease maintenance tasks like pip distribution and milestones management.

**Comment by superbobry** [comment]
I hope git has a way of doing it without losing history ...

**Comment by svinota** [comment]
Yes, shure, but I should change the packaging scheme for ALT Linux distributions as well. This will take some time.

**Comment by svinota** [comment]
started.

new repos:
- cxnet -- netlink and co
- py9p -- 9P lib by Andrey Mirtchovski

next steps: split out apps repos (like statfs and so on)
